---
:concurrency: 3
:queues:
  - kiotviet_development_default
staging:
  :concurrency: 3
  :queues:
    - kiotviet_staging_default
production:
  :concurrency: 3
  :queues:
    - kiotviet_production_default
